name: Spotify-XRAY

services:
  spotify-xray:
    build:
      context: .
      dockerfile: Dockerfile
    image: 271122/spotify-xray:latest
    container_name: spotify-xray
    ports:
      - "80:80"

    env_file:
      - .env

    depends_on:
      - redis


  redis:
    image: redis:8.2-rc1-alpine3.22
    container_name: redis
    ports:
      - "6379:6379"
    entrypoint: ["redis-server"]
    command: ["--requirepass", "password"] # WARNING: Change password before running

    env_file:
      - .env