apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xray-server
  namespace: spotify-xray
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spotify-xray
    spec:
      containers:
      - name: spotify-xray
        image: 271122/spotify-xray