apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xray-ingress
  namespace: spotify-xray
spec:
  ingressClassName: nginx
  rules:
  - host: localhost # Change to your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spotify-xray
            port:
              number: 80
